import type { MailJob } from './dropSheetService';

export const SEED_JOBS: MailJob[] = [
    // Table A: Bally's Lincoln (Dec 2025 - Historical Context)
    {
        id: 'lincoln-dec-core-12pg',
        campaign_name: 'Dec Slot Core Bklt - 12 pg',
        mail_type: 'Core/Newsletter',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 44801,
        in_home_date: '2025-11-17',
        first_valid_date: '2025-12-01',
        vendor_mail_date: '2025-11-03', // Actual mail date inferred from table if matched? Or simulate. Let's assume on time.
        milestones: {
            outline_given: '2025-10-20T09:00:00Z',
            data_received: '2025-10-25T09:00:00Z',
            data_approved: '2025-10-26T09:00:00Z',
            creative_received: '2025-10-27T09:00:00Z',
            creative_approved: '2025-10-30T09:00:00Z',
            sent_to_vendor: '2025-11-01T09:00:00Z',
            mailed: '2025-11-03T09:00:00Z'
        },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-dec-core-8pg',
        campaign_name: 'Dec Slot Core Bklt - 8 pg',
        mail_type: 'Core/Newsletter',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 15585,
        in_home_date: '2025-11-17',
        first_valid_date: '2025-12-01',
        vendor_mail_date: '2025-11-03',
        milestones: { mailed: '2025-11-03T09:00:00Z' }, // Minimal history
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-lucky-free-bet',
        campaign_name: 'Lucky Free Bet Postcard',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 6265,
        in_home_date: '2025-11-21',
        first_valid_date: '2025-12-05',
        vendor_mail_date: '2025-11-07',
        milestones: { mailed: '2025-11-07T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-champions-slots',
        campaign_name: 'Champions Event Slots',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 364,
        in_home_date: '2025-11-24',
        first_valid_date: '2025-12-06',
        vendor_mail_date: '2025-11-10',
        milestones: { mailed: '2025-11-10T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-champions-tables',
        campaign_name: 'Champions Event Tables',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 156,
        in_home_date: '2025-11-24',
        first_valid_date: '2025-12-06',
        vendor_mail_date: '2025-11-10',
        milestones: { mailed: '2025-11-10T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-legends-tables',
        campaign_name: 'Legends Event Tables',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 790,
        in_home_date: '2025-11-24',
        first_valid_date: '2025-12-06',
        vendor_mail_date: '2025-11-10',
        milestones: { mailed: '2025-11-10T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-legends-slots',
        campaign_name: 'Legends Event Slots',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 2093,
        in_home_date: '2025-11-24',
        first_valid_date: '2025-12-06',
        vendor_mail_date: '2025-11-10',
        milestones: { mailed: '2025-11-10T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-dec-lucky-3panel',
        campaign_name: 'Dec Lucky Free Bet (3-Panel)',
        mail_type: 'Tri-Fold',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 4376,
        in_home_date: '2025-11-17',
        first_valid_date: '2025-12-01',
        vendor_mail_date: '2025-11-03',
        milestones: { mailed: '2025-11-03T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-dec-lucky-2panel',
        campaign_name: 'Dec Lucky Free Bet (2-Panel)',
        mail_type: 'Bi-Fold',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 8960,
        in_home_date: '2025-11-17',
        first_valid_date: '2025-12-01',
        vendor_mail_date: '2025-11-03',
        milestones: { mailed: '2025-11-03T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-vip-host-dinner',
        campaign_name: '12/11 PD VIP Host Dinner',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 6847,
        in_home_date: '2025-12-08',
        first_valid_date: '2025-12-20',
        vendor_mail_date: '2025-11-24',
        milestones: { mailed: '2025-11-24T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-nye-invite',
        campaign_name: 'New Years Eve Invite',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-15',
        first_valid_date: '2025-12-27',
        vendor_mail_date: '2025-12-01',
        milestones: { mailed: '2025-12-01T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-first-chance',
        campaign_name: 'FIRST Chance Carnival',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-11-21',
        first_valid_date: '2025-12-05',
        vendor_mail_date: '2025-11-07',
        milestones: { mailed: '2025-11-07T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-second-chance',
        campaign_name: '2nd Chance Carnival',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-15',
        first_valid_date: '2025-12-27',
        vendor_mail_date: '2025-12-01',
        milestones: { mailed: '2025-12-01T09:00:00Z' },
        created_at: new Date().toISOString()
    },

    // Table B: Bally's Tiverton (Dec 2025 - Historical Context)
    {
        id: 'tiverton-dec-core-8pg',
        campaign_name: 'Dec Slot Core 8 Pg Bklt',
        mail_type: 'Core/Newsletter',
        property: 'Tiverton',
        job_submitted: true,
        postage: 'Standard',
        quantity: 4473,
        in_home_date: '2025-11-17',
        first_valid_date: '2025-12-05',
        vendor_mail_date: '2025-11-03',
        milestones: { mailed: '2025-11-03T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'tiverton-dec-core-12pg',
        campaign_name: 'Dec Slot Core 12 Pg Bklt',
        mail_type: 'Core/Newsletter',
        property: 'Tiverton',
        job_submitted: true,
        postage: 'Standard',
        quantity: 16889,
        in_home_date: '2025-11-17',
        first_valid_date: '2025-12-05',
        vendor_mail_date: '2025-11-03',
        milestones: { mailed: '2025-11-03T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'tiverton-dec-he-gc-slots',
        campaign_name: 'Dec HE GC Slots',
        mail_type: '6x9 Postcard',
        property: 'Tiverton',
        job_submitted: true,
        postage: 'Standard',
        quantity: 736,
        in_home_date: '2025-12-02',
        first_valid_date: '2025-12-20',
        vendor_mail_date: '2025-11-18',
        milestones: { mailed: '2025-11-18T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'tiverton-dec-he-gc-tables',
        campaign_name: 'Dec HE GC Tables',
        mail_type: '6x9 Postcard',
        property: 'Tiverton',
        job_submitted: true,
        postage: 'Standard',
        quantity: 449,
        in_home_date: '2025-12-02',
        first_valid_date: '2025-12-20',
        vendor_mail_date: '2025-11-18',
        milestones: { mailed: '2025-11-18T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'tiverton-dec-lucky-free-bet',
        campaign_name: 'Dec Lucky Free Bet',
        mail_type: '6x9 Postcard',
        property: 'Tiverton',
        job_submitted: true,
        postage: 'Standard',
        quantity: 5541,
        in_home_date: '2025-11-18',
        first_valid_date: '2025-12-06',
        vendor_mail_date: '2025-11-04',
        milestones: { mailed: '2025-11-04T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'tiverton-first-chance',
        campaign_name: '12/5-6 First Chance Carnival',
        mail_type: '6x9 Postcard',
        property: 'Tiverton',
        job_submitted: true,
        postage: 'Standard',
        quantity: 10865,
        in_home_date: '2025-11-17',
        first_valid_date: '2025-12-05',
        vendor_mail_date: '2025-11-03',
        milestones: { mailed: '2025-11-03T09:00:00Z' },
        created_at: new Date().toISOString()
    },

    // Table C: Bally's Lincoln (Jan 2026 - Active Foundation)
    {
        id: 'lincoln-jan-core-8pg',
        campaign_name: 'Jan Slot Core Bklt - 8 pg',
        mail_type: 'Core/Newsletter',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-12',
        first_valid_date: '2026-01-01',
        vendor_mail_date: '',
        milestones: { outline_given: '2025-11-01T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-jan-lucky-free-bet',
        campaign_name: 'Jan Lucky Free Bet Postcard',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: true,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-15',
        first_valid_date: '2026-01-02',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-jan-champions-tables',
        campaign_name: 'Champions Event Tables',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-17',
        first_valid_date: '2026-01-06',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-jan-champions-slots',
        campaign_name: 'Champions Event Slots',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-17',
        first_valid_date: '2026-01-06',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-jan-legends-tables',
        campaign_name: 'Legends Event Tables',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-17',
        first_valid_date: '2026-01-06',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-jan-legends-slots',
        campaign_name: 'Legends Event Slots',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-17',
        first_valid_date: '2026-01-06',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-jan-lucky-3panel',
        campaign_name: 'Lucky Free Bet (3-Panel)',
        mail_type: 'Tri-Fold',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2026-01-12',
        first_valid_date: '2026-01-30',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-jan-lucky-2panel',
        campaign_name: 'Lucky Free Bet (2-Panel)',
        mail_type: 'Bi-Fold',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2026-01-13',
        first_valid_date: '2026-01-31',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-ri-tier-upgrade',
        campaign_name: 'RI Tier Upgrade',
        mail_type: 'Tri-Fold',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2026-01-08',
        first_valid_date: '2026-01-28',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-pd-experience',
        campaign_name: 'PD Experience Event',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-31',
        first_valid_date: '2026-01-20',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'lincoln-asian-pd-gc',
        campaign_name: 'Asian PD GC Event',
        mail_type: '6x9 Postcard',
        property: 'Lincoln',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2026-01-07',
        first_valid_date: '2026-01-27',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },

    // Table D: Bally's Tiverton (Jan 2026 - Active Foundation)
    {
        id: 'tiverton-jan-core-8pg',
        campaign_name: 'Jan Slot Core 8 Pg Bklt',
        mail_type: 'Core/Newsletter',
        property: 'Tiverton',
        job_submitted: true,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-12',
        first_valid_date: '2026-01-01',
        vendor_mail_date: '',
        milestones: { outline_given: '2025-11-01T09:00:00Z' },
        created_at: new Date().toISOString()
    },
    {
        id: 'tiverton-jan-he-gc-slots',
        campaign_name: 'Jan HE GC Slots',
        mail_type: '6x9 Postcard',
        property: 'Tiverton',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-17',
        first_valid_date: '2026-01-06',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'tiverton-jan-he-gc-tables',
        campaign_name: 'Jan HE GC Tables',
        mail_type: '6x9 Postcard',
        property: 'Tiverton',
        job_submitted: false,
        postage: 'Standard',
        quantity: 0,
        in_home_date: '2025-12-17',
        first_valid_date: '2026-01-06',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    },
    {
        id: 'tiverton-jan-lucky-free-bet',
        campaign_name: 'Jan Lucky Free Bet',
        mail_type: '6x9 Postcard',
        property: 'Tiverton',
        job_submitted: false,
        postage: 'First Class',
        quantity: 0,
        in_home_date: '2025-12-17',
        first_valid_date: '2026-01-06',
        vendor_mail_date: '',
        milestones: {},
        created_at: new Date().toISOString()
    }
];
